
    <div style="background-image: linear-gradient(#A5A5A5,rgb(28, 25, 151))">
<div class="services" id="services">
<h3 class="title">Odaberi igrača</h3>

<div class="diff_services">
<div class="diff_service_item">
<a href="<?=App::config('url')?>index/messistatistika" style="color:darkblue"><img src="<?=App::config('url')?>public/img/messi.jpg" alt="Messi">
<h5>Lionel Messi</h5></a>
</div>


<div class="diff_service_item">
<a href="playerbaseney.php" style="color:darkblue"><img src="<?=App::config('url')?>public/img/neymi.jpg" alt="Neymar">
<h5>Neymar</h5></a>
</div>

<div class="diff_service_item">
<a href="playerbasemessi.php" style="color:darkblue"><img src="<?=App::config('url')?>public/img/lewaa.jpg"  alt="Lewandowski">
<h5>Robert Lewandowski</h5></a>
</div>
</div>
</div>

<div class="services" id="services">
<div class="diff_services">
<div class="diff_service_item">
<a href="playerbasemessi.php" style="color:darkblue"><img src="<?=App::config('url')?>public/img/salah.jpg" alt="Salah">
<h5>Mohamed Salah</h5></a>
</div>

<div class="diff_service_item">
<a href="playerbasemessi.php" style="color:darkblue"><img src="<?=App::config('url')?>public/img/auba.jpg" alt="Aubameyang">
<h5>Pierre-Emerick Aubameyang</h5></a>
</div>

<div class="diff_service_item">
<a href="playerbasemessi.php" style="color:darkblue"><img src="<?=App::config('url')?>public/img/hal.jpg" alt="Haaland">
<h5>Erling Braut Haaland</h5></a>
</div>
</div>
</div>
</div>

   
