
<body>

    <p class="modre"><b>City De Bruyneu ponudio novi, poboljšani ugovor. Belgijac ga odbio</b></p>
    <p class="pomoc"><i class="malovecee">KEVIN DE BRUYNE je odbio novi, poboljšani ugovor koji mu je ponudio Manchester City. Tu su vijest objavili engleski mediji.</i>
    <p class="modric">
    <img src="<?=App::config('url')?>public/img/bruyne.jpg" alt="Bruyne"></a></p>
<p class="modree">Belgijski veznjak trenutačno zarađuje 280.000 funti tjedno, što je oko 15 milijuna godišnje, a bogati klub ponudio mu je navodno iste ili tek malo bolje uvjete za potpis na novi petogodišnji  ugovor. No Belgijac, bez obzira na pandemiju i probleme koji su došli s njom, očekuje značajniju povišicu i želi biti najbolje plaćeni nogometaš u momčadi.</p>
<p class="ramoss">Uprava Cityja želi jednog od najboljih ofenzivaca svijeta vezati za sebe te mu je ponudila novi ugovor koji mu je garantirao veću plaću.</p>
<p class="ramoss">Trenutačni ugovor vrijedi mu još dvije i pol sezone, do ljeta 2023. godine, a De Bruyne je nekoliko puta izražavao naklonost prema klubu i gradu, pa se vjeruje da želi ostati.</p>
<p class="modric">
<div class="text-center">
<img src="<?=App::config('url')?>public/img/tablicaeng.png" alt="Tablica"></a></p></div>
<p class="ramoss">Uz ovu navodnu tezu vezanu za ponajboljeg veznjaka, čini se kako City napokon uspijeva povezivati dobre partije, te su zasada zaredali 3 pobjede i zauzeli 5. mjesto sa dvije utakmice zaostatka za vodećim Liverpoolom.</p>

</body>