

<p class="messi"><b>
PELE OTIŠAO U POVIJEST, MESSI SINOĆ POSTAVIO NOVI REKORD GOLOM PROTIV VALLADOLIDA!</b></p>
<div class="nista">
<p class="podnaslov"><i>Barcelona je slavila, a Leo Messi oborio je rekord legendarnog Pelea;
nitko u povijesti nije zabio više golova za istu momčad</i></p>
<p class="pomoc"><a href="https://www.tportal.hr/media/thumbnail/900x540/1375093.jpeg?cropId=1568042">
<img src="https://www.tportal.hr/media/thumbnail/900x540/1375093.jpeg?cropId=1568042" height="900" width="600"></a></p>
<p class="pomoc"><b>Nogometaši Barcelone slavili su 3:0 na 
gostovanju kod Valladolida u utakmici 16. kola španjolske La Lige</b></p>
<div class="padlf"><p class="pomoc">Efikasno izdanje katalonske momčadi nagovijestio je francuski branič 
Lenglet golom za vodstvo gostiju u 21. minuti.
Na 2:0 je u 35. minuti prednost Barcelone povećao Nizozemac Braithwaite.
<p class="pomoc">U nastavku se u strijelce upisao i Leo Messi koji je golom u 65. minuti 
postao rekorderom po broju golova za jednu momčad (644), nadmašivši legendarnog Brazilca Pelea s 
kojim se izjednačio prije tri dana, 
kad je zabio u prvenstvenom dvoboju s Valencijom.</p>
</div>
<p class="pomoc"><a href="https://images.daznservices.com/di/library/GOAL_INTERNATIONAL/2a/9d/pele-messi_faru94uf082w1ghebowxuz7qc.jpg?t=-1525703531&quality=60&w=1200&h=800">
<img src="https://images.daznservices.com/di/library/GOAL_INTERNATIONAL/2a/9d/pele-messi_faru94uf082w1ghebowxuz7qc.jpg?t=-1525703531&quality=60&w=600&h=600" ></a></p>
<p class="pele1"><i>“Kad je tvoje srce puno ljubavi, teško je promijeniti put. 
Baš kao i ti, znam kako je nositi isti dres svaki dan. Kao i ti, 
znam da nijedno mjesto nije tako dobro kao ono u kojem se osjećaš kao kod kuće. 
Čestitam na povijesnom rekordu, Lionel. Ali iznad svega, čestitam na prekrasnoj karijeri u Barceloni. Priče poput naše, da volimo momčad toliko dugo, 
nažalost su rijetkost u nogometu. Divim ti se”, napisao je Pele.</i></p>
