
<body>

    <p class="modre"><b>KAKAV NAKLON HRVATSKOM MAESTRU? ‘IMA 35, PA ŠTO? ON JE SIMBOL REALA, 
    ŠTO JE STARIJI TO JE BOLJI!‘</b></p>
    <p class="pomoc"><i class="malovece">Marca se dotaknula briljantne Modrićeve forme i to strogo biranim riječima njihova novinara.</i>
    <p class="pomoc"><a href="https://static.jutarnji.hr/images/slike/2021/01/04/f_5885813_1024.jpg?2021-01-04-15-15-45">
<img src="https://static.jutarnji.hr/images/slike/2021/01/04/f_5885813_1024.jpg?2021-01-04-15-15-45" width="600" height="600"></a></p>
<p class="modree">
Kapetan hrvatske nogometne reprezentacije Luka Modrić svojim izvedbama iz utakmice u utakmicu 
ne prestaje fascinirati španjolsku, posljedično i svjetsku nogometnu javnost. 
Njegove recentne partije razlog su bile novog teksta u španjolskom sportskom dnevniku Marca. 
Posvetili su mu priču pod naslovom "Kog je briga kada je Modrić rođen?".</p>
<p class="modree">U tom tekstu Marca se divi njegovim nogometnim majstorijama. 
Također, ističu važnost tog lista u pokušajima da se nagovori upravu Reala na produljenje ugovora s Modrićem. 
Na taj način, suradnja Kraljevskog kluba i bivše "Zlatne lopte" završava u lipnju 2022. godine.</p>
<p class="modree">- Njegova putovnica svjedoči da je rođen 1985., 
ali koga je uopće briga za to? Modrić je primjer za duplo mlađe klince koji ulaze u svijet profesionalnog nogometa. 
S 35 godina Modrić je igrač zbog kojeg plaćate ulaznicu i pretplatu za kabelsku televiziju - pišu Španjolci.</p>
<p class="pomoc"><a href="https://static.jutarnji.hr/images/slike/2021/01/04/6007839.jpg?1609773344">
<img src="https://static.jutarnji.hr/images/slike/2021/01/04/6007839.jpg?1609773344" width="600" height="600"></a></p>
<p class="modree">I ove je sezone Modrić glavni motor Realovog uspjeha, s njime će se Kraljevi upustiti u šampionsku utrku s gradskim rivalima iz Atletica koji je glavni konkurent za titulu.</p>
<p class="modree">- Ono što Modrić na terenu radi ne može biti napravljeno bolje. S više talenta, sigurnosti, stila, kvalitete i nogometne zrelosti. Kod njega nema ni trunke sebičnosti, bahatosti, samo stalna opsjednutost time kako pomoći momčadi. Modrić je pojedinac, ali on utjelovljuje i simbolizira Realovu kolektivnu igru. Što je stariji sve je bolji, pa čak i efikasniji - piše u Marci.</p>

</body>
