
<body>
    
        <div class="clanakneymar">
        <p class="bitno"><b>‘NEĆE BITI 500 LJUDI, NEGO SAMO 150‘ NEYMAR IZAZVAO ZGRAŽANJE U ELITNOM GRADU, 
            ŠTO ČEKA NOVOG TRENERA?</p></b>
            <p class="manjifont">Potjerani trener dobio je još jednu godišnju plaću, 
               a najveća zvijezda glavna je tema u Brazilu...</p>     
</div>
<div>
<p class="pomoc"><a href="https://static.jutarnji.hr/images/slike/2020/12/28/6007643.jpg?1609242003">
<img src="https://static.jutarnji.hr/images/slike/2020/12/28/6007643.jpg?1609242003" height="300" width="400"></a></p>
</div>
<div class="clanakneymarr">
<p class="tuchel">Thomas Tuchel je prošlost, 47-godišnji Nijemac, 
koji je od 2018. do 2020. godine od 127 utakmica na klupi Paris Saint Germaina dobio njih 95,
na odmoru je nakon otkaza u Parizu prije pet dana. 
Tuchel je dobio 75 posto dvoboja s Parižanima.
Tuchela više ništa ne veže s PSG-om nakon što su se odvjetnici suprotstavljenih strana 
uspjeli dogovoriti oko odštete koju će dobiti. 
U novogodišnjim praznicima njemački će stručnjak uživati s novim iznosom koji se kreće 
između 7 i 8 milijuna eura, otkrili su mediji iz njegove domovine. 
Toliko mu je, otprilike, bila i godišnja plaća...</p>
<p class="tuchell">Nijemca ce nasljediti Argentinac Mauricio Pochettino,
48-godišnjak koji je u trenerskoj karijeri od 2009. vodio tek tri kluba, Espanyol, Southampton 
i Tottenham, 
sve je dogovorio s Leonardom i postat će peti trener PSG-a zaposlen od strane Kataraca.
<p><a class="pomoc" href="https://static.jutarnji.hr/images/slike/2020/12/28/6007677.jpg?1609242003">
<img src="https://static.jutarnji.hr/images/slike/2020/12/28/6007677.jpg?1609242003" height="300" width="400"></a></p>
<p class="tuchell">I dok novi trener slaže svoj trijumfalni plan, njegov ključni igrač uživa u domovini. 
Neymar je slobodno vrijeme preko praznika odlučio provesti ludo se zabavljajući s prijateljima u 
Brazilu. Za 28-godišnjeg brazilskog napadača nije to ništa novo, svake zime s Neymarom je ista priča. 
Niti jedna ne može proći bez njegovih razularenih zabava.</p>
<p class="tuchel">Jedne brazilske novine su objavile kako je Neymar za kraj 2020. pripremio
tulum koji će trajati pet dana u svojoj vili u Rio de Janeiru, te se navodno najavljuje oko
500-tinjak gostiju.
<p><a class="pomoc" class="neyslika" href="https://static.jutarnji.hr/images/slike/2020/12/28/6023853.jpg"> <img src="https://static.jutarnji.hr/images/slike/2020/12/28/f_6023853_1024.jpg?2020-12-29-11-40-03" width="600" height="600" >
          </a></p>
<p class="tuchel">Priču je pokušala smiriti agencija Fabrica, 
koja je za Neymara organizirala zabavu u elitnoj Mangaratibi. 
Radi se o gradiću od 40-ak tisuća stanovnika u državi Rio de Janeiro, 
u kojem zbog mjera ove zime neće biti organizirane proslave za Novu godinu.
<p class="tuchel">- To je naša zabava, i nije povezana s Neymarom! 
Zabava će se održati prema zdravstvenim standardima koje propisuju vlasti. 
I na njoj neće biti 500 gostiju,
već samo 150 gostiju - poručili su iz Fabrice o toj temi.</p>
</div>

</body>