<div id="page-container">
<div class="grid container paragraf">
    <div class="callout small">
    <a href="<?=App::config('url')?>index/modric"><h5><b>KAKAV NAKLON HRVATSKOM MAESTRU? ‘IMA 35, PA ŠTO? ON JE SIMBOL REALA,
     ŠTO JE STARIJI TO JE BOLJI!‘</h5></b>
  <p>Marca se dotaknula briljantne Modrićeve forme i to strogo biranim riječima njihova novinara.</a></p>
  
</div>
<div class="callout small">
<a href="<?=App::config('url')?>index/osdin"><h5><b>DRUŠTVO IZ OSIJEKA IZBACILO DINAMOVCE IZ HOTELA: 
    JE LI ROVINJ DOVOLJNO VELIK GRAD ZA MAMIĆA I BJELICU?</b></h5>
  <p>Dinamo i Osijek, dva vodeća kluba u državi, pripremat će se na istom mjestu za nastavak sezone...</a></p>

</div>
</div>
   </div>
