
<body>
      
    <p class="modric"><a href=https://static.jutarnji.hr/images/slike/2021/01/02/f_5831921_1024.jpg?2021-01-04-13-17-30>
<img src="https://static.jutarnji.hr/images/slike/2021/01/02/f_5831921_1024.jpg?2021-01-04-13-17-30" width="600" height="600"></a></p>
<p class="modre"><b>DRUŠTVO IZ OSIJEKA IZBACILO DINAMOVCE IZ HOTELA: 
JE LI ROVINJ DOVOLJNO VELIK GRAD ZA MAMIĆA I BJELICU?</b></p>
<p class="pomoc"><i class="malovece">Dinamo i Osijek, dva vodeća kluba u državi, pripremat će se na istom mjestu...</i></p>
<p class="modreee">
Dinamo i Osijek dijelit će Rovinj na zimskim pripremama. 
Hoće li ovaj istarski gradić biti premali za dva vodeća kluba u HNL-u?
Otprilike kao kad u vestern filmovima revolveraš ulazi u saloon, 
razmiče pokretna vrata i kaže drugom revolverašu “ovaj grad je premali za nas dvojicu”. 
Nakon toga iz futrole se izvlače pištolji. U Rovinju se neće pucati, ali tko zna, 
da su Mamić i Bjelica živjeli u ona vremena na Divljem zapadu, ne bismo se kladili...</p>
<p class="modree">U ovom slučaju, međutim, neće biti buke. 
Dinamo i Osijek će se vjerojatno izbjegavati. 
Ako i dođe do nekog slučajnog susreta, bit će slike, teško i tona. 
Priču sigurno znate, ali ako netko ne zna, ponoviti ćemo ukratko. Nakon što je Bjelica otišao iz Maksimira, Mamić je ustvrdio kako mu ne smeta što su njegovi igrači i dalje u kontaktu s Bjelicom, 
ali mu smeta što njegov donedavni suradnik pokušava - destabilizirati klub.</p>
<p class="modree">- Neosporno je da je bio njihov trener i da imaju odličan odnos.
 Čujem se i ja s bivšim igračima. 
 Nemam problema s tim da se čuju, ali nije korektno da on to izjavljuje u novinama. To je pokušaj destabilizacije. On je vrlo pametan, radi na svom marketingu i treba mu čestitati, 
ali to nije fer prema dečkima - kazao je tada Mamić.</p>
<p class="pomoc"><b>Trener Osijeka je odgovorio na društvenim mrežama...</b>
<i>- Dok se gori bave boljima, bolji se bave sobom. Zato su i bolji.</p></i>
<p class="modreee">Mamić i Bjelica bili su na suprotnim stranama i u onom slučaju smanjenja plaća, tako da je za pretpostaviti da će se zasigurno - izbjegavati.</p>
<p class="modric"><img src="tablica.png" alt=""></p>

</body>