
<body>

<div class="clanakpetrinja">
<p class="bitno"><b>U PETRINJU STIGLI I BBB-I, POMOĆ PRIKUPLJA I TORCIDA! SPORTAŠI SHRVANI: 
‘DRŽITE SE DRAGI LJUDI...‘</b></p>
<p class="bitno"><b>Nekome smo se zamjerili. Žao mi je svih ljudi koji proživljavaju ove strahove - 
napisao je Lovren</p></b>
</div>
<div>
<p class="font" >Bivši prvoligaš iz Vinkovaca udružio se u humanitarnu akciju.</p>
<div>
<p class="pomoc"><a href="https://static.jutarnji.hr/images/slike/2020/12/29/6026287.jpg">
<img src="https://static.jutarnji.hr/images/slike/2020/12/29/6026287.jpg?1609279307" width="300" height="300"></a>
</p>
</div>
</div>
<div class="bot">
<p><b>>>> Navijači Dinama, popularna skupina BBB, organiziraju i za srijedu akciju za Petrinju. 
Prenosimo poruku u cijelosti:
"POMOĆ ZA PETRINJU! ❤️</b>
Sutra ujutro krećemo za Petrinju odvesti namirnice, deke, poplune, 
jastuke, potrebnu robu (topla odjeća) koja se prikuplja. 
<p>➡️ MOLIMO sve koji mogu da se pridruže pomoći!!!</p>
<p>➡️ 30.12. srijeda</p>
<p>- 08.00h pokret iz Novog Jelkovca i Sesvete</p>
<p>- 08.30h pokret s Ravnica</p>
<p>- 09.00h pokret iz Novog Zagreba - Dugave</p>
<p>Svi koji se žele priključiti akciji mogu s nama put k Petrinji 
(ponijeti lopate, rukavice i dobru volju!)</p></p>
</div>

</body>