<div id="page-container">
<div class="grid container paragraf">
      <div class="grid-x grid-margin-x" >
        <div class="large-4 cell">
          <div class="callout tijelo" >
          <a class="clanakpetrinjaa" href="<?=App::config('url')?>index/petrinja">
          <p class="bitno"><b>
          UŽIVO: HRVATSKI SPORTAŠI ŠALJU PORUKE PODRŠKE! PREMA PETRINJI KRENULI BBB-I, 
          TORCIDA PRIKUPLJA POMOĆ.</b></p>
          <p class="fontt">Razoran potres s epicentrom kod Petrinje koji se oko 12 sati osjetio diljem Hrvatske bio je jačine 6,2 po Richteru, izvijestila je Seizmološka služba. 
          Materijalna šteta u Petrinji je ogromna, puno objekata je razrušeno.<p>
           <p><i>Porukama podrške pridružili su se i Ivan Klasnić te Mateo Kovačić.</i></p></a>
           <div class="slika">
           <a class="slikakova" href="https://static.jutarnji.hr/images/slike/2020/12/29/6024777.jpg">
           <img src="https://static.jutarnji.hr/images/slike/2020/12/29/6024777.jpg" alt="Kovacic" width="400" height="400"></a>
          </div>
<div class="razmak">
<a class="slikaivank" href="https://static.jutarnji.hr/images/slike/2020/12/29/6024775.png">
<img src="https://static.jutarnji.hr/images/slike/2020/12/29/6024775.png" alt="Uredu"width="400" height="400" ></a>
</div>
          </div>
        </div>
        <div class="large-4 cell">
          <div class="callout tijelo" >
          <a class="neymar" href="<?=App::config('url')?>index/neymar"><p class="bitno"><b>
          ‘NEĆE BITI 500 LJUDI, NEGO SAMO 150‘ NEYMAR IZAZVAO ZGRAŽANJE U ELITNOM GRADU, 
          ŠTO ČEKA NOVOG TRENERA?</p></b>
          <p class="fontt">Nakon otkaza Thomasa Tuchela, kormilo pariškog kluba će preuzeti 48-godišnji argentinski stručnjak 
            Mauricio Pochettino.
          <p class="fontt">Dok novi trener slaže svoj trijumfalni plan, njegov ključni igrač uživa u domovini. 
          Neymar je slobodno vrijeme preko praznika odlučio provesti ludo se zabavljajući s prijateljima u Brazilu. 
          Za 28-godišnjeg brazilskog napadača nije to ništa novo, svake zime s Neymarom je ista priča.
          Niti jedna ne može proći bez njegovih razularenih zabava.</p>
          </p></a>
          <div class="slika1">
           <a class="neyslika" href="https://static.jutarnji.hr/images/slike/2020/12/28/6023853.jpg"> <img src="https://static.jutarnji.hr/images/slike/2020/12/28/f_6023853_1024.jpg?2020-12-29-11-40-03" alt="Neymii" width="600" height="600" >
          </a>
          </div>
          </div>
          </div>
        <div class="large-4 cell">
          <div class="callout tijelo" >
          <a class="messi" href="<?=App::config('url')?>index/messi"><p class="bitno"><b>
          PELE OTIŠAO U POVIJEST, MESSI SINOĆ POSTAVIO NOVI REKORD GOLOM PROTIV VALLADOLIDA!</b>
          <p class="fontt">Barcelona je u utorak navečer slavila protiv Valladolida s 0:3 u 15. kolu Prmiere, 
            a treći gol na susretu u 65. minuti zabio je Lionel Messi.</p>
            <p class="fontt">Čudesni Argentinac tako je srušio još jedan veliki rekord u svojoj karijeri.
            “Čestitam na povijesnom rekordu, Lionel. Čestitam na prekrasnoj karijeri u Barceloni. 
            Priče poput naše, da volimo momčad toliko dugo, nažalost su rijetkost u nogometu. 
            Divim ti se”, riječi su kojima je Pele čestitao novom rekorderu.
            </p></a>
            <div class="slikamessi">
              <a class="messislika" href="https://static.jutarnji.hr/images/slike/2020/12/22/o_6001425_1280.jpg"><img src="https://static.jutarnji.hr/images/slike/2020/12/22/o_6001425_1280.jpg" alt="Messii" width="600" height="600">
            </a>
            </div>
          </div>
        </div>
</div>
</div>
</div>
