
<body>

    <p class="modre"><b>Ramos poručio Perezu: PSG mi je rekao da želi dovesti mene i Messija</b></p>
    <p class="pomoc"><i class="malovecee">Kapetan Sergio Ramos odbija potpisati s aktualnim prvakom Španjolske.</i></p>
    <p class="pomoc"><a href="https://www.tportal.hr/media/thumbnail/w1000/1379992.jpeg">
<img src="https://www.tportal.hr/media/thumbnail/w1000/1379992.jpeg" width="600" height="600"></a></p>
<p class="modree">Iako mu "kraljevski" klub nudi jednogodišnji ugovor s pravom produljenja na još jednu godinu, kapetan to odbija.
Prvenstveno zato što mu klub ne želi odmah dati dvogodišnji ugovor, a onda i zbog toga što mu godišnju plaću želi smanjiti za 10 posto. 
Ramos u ovom trenutku zarađuje 15 milijuna eura godišnje.</p>
<h3 class="ramos">Ramos je Perezu dao do znanja kako će slušati ponude drugih klubova</h3>
<p class="ramoss"> Jučer je u televizijskoj emisiji El Chiringuito poznati španjolski novinar Josep Pedrerol kazao kako su se predsjednik Florentino Perez i kapetan Ramos na temu novog ugovora sastali prošle srijede prije utakmice protiv Elchea.</p>
<p class="ramoss">Ramos je predsjedniku kluba dao do znanja kako neće prihvatiti ponudu koju je pred njega stavio klub te kako je spreman slušati ponude drugih klubova. Naime, Ramos je ušao u posljednjih pola godine ugovora i može pregovarati s drugim klubovima o besplatnom napuštanju Reala na ljeto.</p>
<p class="modric"><a href="https://sportklub.hr/wp-content/uploads/2019/03/gettyimages-1127967356-89227-750x610.jpeg">
<img src="https://sportklub.hr/wp-content/uploads/2019/03/gettyimages-1127967356-89227-750x610.jpeg" width="600" height="600"></a></p>
<h3 class="ramos">PSG želi dovesti Ramosa i Lionela Messija potpuno besplatno.</h3>
<p class="ramoss">Uz navedeno, branič Reala je Florentinu Perezu rekao kako mu je netko iz Paris Saint-Germaina predstavio plan prema kojemu će francuski klub na ljeto dovesti njega i Lionela Messija potpuno besplatno.</p>
<p class="ramoss">Perez na to nije imao spreman odgovor te je Ramosu kratko dometnuo kako može ići ako dobije ponudu koja će ga zadovoljiti. Razumljivo, vijest je odmah dospjela na svjetske naslovnice, a jutros je i France Football na naslovnici imao veliki plan PSG-a za dovođenje najvećih zvijezda Reala i Barcelone. Ipak, u prvom planu je bio novi trener Mauricio Pochettino koji bi trebao osvajoti toliko željenu Ligu prvaka. Ako ne ove, onda sljedeće sezone, kada bi zvjezdani dvojac trebao stići.</p>

</body>