

<main>
<div id="page-container">
<div class="grid container paragraf">
<div class="row medium-unstack">
  <div class="column medium-4">
    <div class="card">
      <div class="card-divider">
      <b>Ramos poručio Perezu: PSG mi je rekao da želi dovesti mene i Messija.</b>
      </div>
      <a href="https://ip.index.hr/remote/indexnew.s3.index.hr/60bea52a-aec5-4af9-8426-284a61aac647.jpg?width=250&height=134&mode=crop&anchor=topcenter&scale=both">
      <img src="https://ip.index.hr/remote/indexnew.s3.index.hr/60bea52a-aec5-4af9-8426-284a61aac647.jpg?width=250&height=134&mode=crop&anchor=topcenter&scale=both" alt="Ramos" height="100" width="100">
</a>
<a href="<?=App::config('url')?>index/ramos"><div class="card-section">
        <h4>Ramos je Perezu dao do znanja kako će slušati ponude drugih klubova.</h4>
        <p>Iako mu Real Madrid nudi novi jednogodišnji ugovor s pravom produljenja na još jednu godinu, kapetan Sergio Ramos odbija potpisati s aktualnim prvakom Španjolske.</a> </p>
 
    </div>
    </div>
  </div>
  
  <div class="row medium-unstack">
  <div class="column medium-4">
    <div class="card">
      <div class="card-divider">
      <b>City De Bruyneu ponudio novi, poboljšani ugovor. Belgijac ga odbio.</b>
      </div>
      <a href="https://ip.index.hr/remote/indexnew.s3.index.hr/1c29db5c-309f-4a29-9ad3-85f430e1a15b.jpg?">
      <img src="https://ip.index.hr/remote/indexnew.s3.index.hr/1c29db5c-309f-4a29-9ad3-85f430e1a15b.jpg?" alt="DeBruyne" height="500" width="300">
</a>
<a href="<?=App::config('url')?>index/bruyne"><div class="card-section">
        <h4>KEVIN DE BRUYNE je odbio novi, poboljšani ugovor koji mu je ponudio Manchester City. Tu su vijest objavili engleski mediji.</h4>
        <p>Trenutačnim ugovorom vezan je za City do ljeta 2023.</a> </p>
 
    </div>
    </div>
  </div>
  </div>
  </div>
</main>


