<form class="log-in-form" action="<?=App::config('url')?>statistika/promjena"
method="POST">
  <h4 class="text-center">Promjena statistike</h4>
  

  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
        <label>Nastupi
          <input type="text" name="nastupi" value="<?=$statistika->nastupi?>">
        </label>
      </div>
      
    <div class="cell large-6">
      <label>Odigrano minuta
        <input type="text"  name="odigranominuta" value="<?=$statistika->odigranominuta?>">
      </label>
    </div>
  </div>
 

  <div class="grid-x grid-padding-x">
    <div class="cell">
      <label>Golovi
        <input type="text" name="golovi" value="<?=$statistika->golovi?>">
      </label>
    </div>
  </div>
  


  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
      <label>Asistencije
        <input type="text" name="asistencije" value="<?=$statistika->asistencije?>">
      </label>
    </div>
    <div class="cell large-6">
      <label>Žuti kartoni
        <input type="text"  name="zutikartoni" value="<?=$statistika->zutikartoni?>">
      </label>
    </div>
  </div>

  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
      <label>Crveni kartoni
        <input type="text" name="crvenikartoni" value="<?=$statistika->crvenikartoni?>">
      </label>
    </div>
    </div>

  <?= $poruka; ?>
  
  <div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
  <a class="alert button expanded" 
  href="<?=App::config('url')?>statistika/index"> Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
  <input type="submit" class="button expanded" value="Promjena"></input>
  </div>
</div>
  <input type="hidden" name="sifra" value="<?=$statistika->sifra?>">
</form>