
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
  <div class="title-bar-title">Izbornik</div>
</div>

<div class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      
      <li><a href="<?=App::config('url')?>index/pocetna">Početna</a></li>
          <li><a href="<?=App::config('url')?>index/novosti">Novosti</a></li>
          <li><a href="<?=App::config('url')?>index/transferi">Transferi</a></li>
      <?php
      if(isset($_SESSION['autoriziran'])): ?>
      <li><a href="<?=App::config('url')?>nadzornaploca/index">Statistika igrača</a></li>
      <li>
      <a href="#">Informacije</a>
        <ul class="vertical menu">
          <li><a href="<?=App::config('url')?>trener/index">Treneri</a></li>
          
          <li><a href="<?=App::config('url')?>zanimljivosti/index">Zanimljivosti</a></li>
          <li><a href="<?=App::config('url')?>statistika/index">Statistika</a></li>
          <li><a href="<?=App::config('url')?>klub/index">Klub</a></li>
          <li><a href="<?=App::config('url')?>igrac/index">Igrač</a></li>
          <?php
          if($_SESSION['autoriziran']->uloga=='admin')://operatere moze vidjet samo admin ?>
          <li><a href="#">Operateri</a></li>
          <?php endif;?>
        </ul>
      </li>
      <?php endif;?>
      </div>
      <div class="top-bar-right">
      
    <ul class="menu">
    <ul class="menu">
      <li><input type="search" placeholder="Traži..."></li>
      <li><button type="button" class="button">Traži</button></li>
    </ul>
      <li>
      <?php
      if(!isset($_SESSION['autoriziran'])): ?>
      <a href="<?=App::config('url')?>index/login">Prijava</a>
      <?php else: ?>
        <a href="<?=App::config('url')?>index/logout">Odjava
      <?=$_SESSION['autoriziran']->ime?>
      <?=$_SESSION['autoriziran']->prezime?>
        </a>
      <?php endif;?>
      </li>
    </ul>
  </div>
</div>
</div>
      



