<form class="log-in-form" action="<?=App::config('url')?>trener/promjena"
method="POST">
  <h4 class="text-center">Promjena postojećeg trenera</h4>
  <div class="grid-x grid-padding-x">
  <div class="cell large-4">
  <label>Ime
    <input type="text" name="ime" value="<?=$trener->ime?>">
  </label>
</div>
  
  <div class="cell large-4">
  <label>Prethodniklub
    <input type="text" name="prethodniklub" value="<?=$trener->prethodniklub?>">
  </label>
  
  </div>
  </div>
  <div class="grid-x grid-padding-x">
  <div class="cell large-4">
  <label>Prezime
    <input type="text" name="prezime" value="<?=$trener->prezime?>">
  </label>
</div>
<div class="cell large-4">
<label>Nacionalnost
<input type="text" name="nacionalnost" value="<?=$trener->nacionalnost?>">
  </label>
</div>
</div>

  <?= $poruka; ?>
  
  <div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
  <a class="alert button expanded" 
  href="<?=App::config('url')?>trener/index"> Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
  <input type="submit" class="button expanded" value="Promjena"></input>
  </div>
</div>
  <input type="hidden" name="sifra" value="<?=$trener->sifra?>">
</form>