<form class="log-in-form" action="<?=App::config('url')?>klub/promjena"
method="POST">
  <h4 class="text-center">Promjena kluba</h4>
  
  <div class="grid-x grid-padding-x">
  <div class="cell">
  <label>Naziv
    <input type="text" name="naziv" value="<?=$entitet->naziv?>">
  </label>
  </div>
  <div class="cell large-4">
  <label>Broj igrača u klubu
    <input type="number" name="brojigracauklubu" value="<?=$entitet->brojigracauklubu?>">
  </label>
  </div>
  </div>
  
  <div class="grid-x grid-padding-x">
  <div class="cell large-4">
  <label>Zanimljivosti
  <select name="zanimljivosti">
          <?php foreach($zanimljivo as $zanimljivosti): ?>
            <option <?php 
              if($entitet->zanimljivosti==$zanimljivosti->sifra){
                echo ' selected="selected" ';
              }
              ?> value="<?=$zanimljivosti->sifra ?>"><?=$zanimljivosti->nazivstadiona . ' ' . $zanimljivosti->kapacitet; ?></option>
          <?php endforeach; ?>
        </select>
  </label>
</div>
</div>
<div class="grid-x grid-padding-x">
<div class="cell large-4">
<label>Trener
<select name="trener">
          <?php foreach($treneri as $trener): ?>
            <option <?php 
              if($entitet->trener==$trener->sifra){
                echo ' selected="selected" ';
              }
              ?> value="<?=$trener->sifra ?>"><?=$trener->ime?> <?=$trener->prezime?></option>
          <?php endforeach; ?>
        </select>
  </label>
</div>
</div>

<div class="grid-x grid-padding-x">
  <div class="cell">
  <div class="callout">
  <?= $poruka; ?>
  </div>
  </div>
  </div>
  
  
  <div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
  <a class="alert button expanded" 
  href="<?=App::config('url')?>klub/index"> Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
  <input type="submit" class="button expanded" value="Promjeni"></input>
  </div>
</div>
<input type="hidden" name="sifra" value="<?=$entitet->sifra?>">
  
</form>