<form class="log-in-form" 
    action="<?=App::config('url')?>zanimljivosti/novo"
    method="POST">
  <h4 class="text-center">Dodavanje zanimljivosti</h4>


  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
      <label>Osnivanje
        <input type="date"  name="osnivanje" value="<?=$zanimljivosti->osnivanje?>">
      </label>
    </div>
  

  
    <div class="cell">
      <label>Naziv stadiona
        <input type="text" name="nazivstadiona" value="<?=$zanimljivosti->nazivstadiona?>">
      </label>
    </div>
  </div>


  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
      <label>Kapacitet
        <input type="number"  name="kapacitet" value="<?=$zanimljivosti->kapacitet?>">
      </label>
    </div>
    </div>
    
  
 
<div class="grid-x grid-padding-x">
    <div class="cell">
     <div class="callout">
      <?=$poruka?>
     </div>
    </div>
  </div>
  

<div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>zanimljivosti/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input>
  </div>
</div>

</form>