<form class="log-in-form" 
    action="<?=App::config('url')?>igrac/novo"
    method="POST">
  <h4 class="text-center">Novi igrač</h4>



  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
        <label>Ime
          <input type="text" name="ime" value="<?=$entitet->ime?>">
        </label>
      </div>
    <div class="cell large-6">
      <label>Prezime
        <input type="text"  name="prezime" value="<?=$entitet->prezime?>">
      </label>
    </div>
    <div class="cell large-6">
      <label>Mjesto rođenja
        <input type="text"  name="mjestorodenja" value="<?=$entitet->mjestorodenja?>">
      </label>
  </div>
  </div>

  <div class="grid-x grid-padding-x">
    <div class="cell">
    <label>Naziv kluba
<select name="klub">
          <?php foreach($klubovi as $klub): ?>
            <option <?php 
              if($entitet->klub==$klub->sifra){
                echo ' selected="selected" ';
              }
              ?> value="<?=$klub->sifra ?>"> <?=$klub->naziv?> 
              </option>
          <?php endforeach; ?>
        </select>
  </label>
    </div>
  </div>


  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
    <label>Statistika
<select name="statistika">
          <?php foreach($statistike as $statistika): ?>
            <option <?php 
              if($entitet->statistika==$statistika->sifra){
                echo ' selected="selected" ';
              }
              ?> value="<?=$statistika->sifra ?>">Nastupi: <?=$statistika->nastupi?> 
               Golovi: <?=$statistika->golovi?>   Asistencije: <?=$statistika->asistencije?></option>
          <?php endforeach; ?>
        </select>
  </label>
    </div>
   
  </div>
  
 
<div class="grid-x grid-padding-x">
    <div class="cell">
     <div class="callout">
      <?=$poruka?>
     </div>
    </div>
  </div>
  

<div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>igrac/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input>
  </div>
</div>

</form>